[package]
name = "zefiro"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "zefiro-cli",
    "zefiro-core",
    "zefiro-core/zefiro-cwl-parser",
    "zefiro-core/zefiro-cwl-js",
    "zefiro-ui"
]